[workspace]
resolver = "2"
members = [
  "crates/forex-search",
  "crates/forex-cli",
  "crates/forex-data",
  "crates/forex-models",
  "crates/forex-core",
  "crates/forex-bindings",
]

[patch.crates-io]
talib-sys = { path = "vendor/talib-sys" }
