[package]
name = "forex-data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
polars = { version = "0.52.0", features = ["lazy", "parquet", "dtype-full", "temporal", "timezones"] }
ndarray = { version = "0.16.1", features = ["rayon"] }
talib = "0.1.2"
talib-sys = "0.1.0"
